windows_task:
  windows_container:
    image: golang:windowsservercore-1803
    os_version: 1803
  env:
    GOPROXY: https://proxy.golang.org
    GOPATH: C:\go
    PATH: ${GOPATH}\bin:${PATH}
    CIRRUS_WORKING_DIR: C:\go\src\github.com\${CIRRUS_REPO_FULL_NAME}
  build_script:
    - go version
    - go build -race -v ./...
  test_script:
    - go test -race -count=100 ./...
    - go test -race -v -count=1 ./...
